- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: psy-model
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: psy-model
    template:
      metadata:
        labels:
          app: psy-model
      spec:
        nodeSelector:
          pool: gpunode
        containers:
          - name: psy-model
            image: psyserviceregistry.azurecr.io/psy-model
            ports:
              - containerPort: 8000
              - containerPort: 11434
            resources:
              requests:
                nvidia.com/gpu: 1
              limits:
                nvidia.com/gpu: 1
- apiVersion: v1
  kind: Service
  metadata:
    name: psy-model-service
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
      - targetPort: 8000
        name: port8000
        port: 8000
        protocol: TCP
      - targetPort: 11434
        name: port11434
        port: 11434
        protocol: TCP
    selector:
      app: psy-model